version: 0.2

phases:
  install:
    commands:
      - echo "Using AWS CLI v2 to deploy static site to S3"
  build:
    commands:
      - echo "Syncing to S3 bucket..."
      - aws s3 sync . s3://comp4964-a4-misuzu --delete \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude "buildspec.yml" \
          --exclude "README.md"
artifacts:
  files:
    - '**/*'
  discard-paths: no
